name: dyntok
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - adlfs==2025.8.0
      - aiobotocore==2.25.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - azure-core==1.36.0
      - azure-datalake-store==0.0.53
      - azure-identity==1.25.1
      - azure-storage-blob==12.27.1
      - bcrypt==5.0.0
      - bleach==6.3.0
      - blobfile==3.1.0
      - bokeh==3.8.1
      - botocore==1.40.70
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - circuitbreaker==2.1.3
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - dask==2025.11.0
      - dataproperty==1.1.0
      - datasets==3.6.0
      - datatrove==0.6.0
      - decorator==5.2.1
      - dill==0.3.8
      - distributed==2025.11.0
      - dropbox==12.0.2
      - dropboxdrivefs==1.4.1
      - evaluate==0.4.6
      - filelock==3.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - fusepy==3.0.1
      - gcsfs==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.6.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanize==4.14.0
      - hydra-core==1.3.2
      - idna==3.11
      - invoke==2.2.1
      - isodate==0.7.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - libarchive-c==5.3
      - linkify-it-py==2.0.3
      - lm-eval==0.4.9.1
      - locket==1.0.0
      - lockfile==0.12.2
      - loguru==0.7.3
      - luigi==3.6.0
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - mbstrdecoder==1.1.4
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - narwhals==2.12.0
      - networkx==3.5
      - ninja==1.13.0
      - nltk==3.9.2
      - numexpr==2.14.1
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - objprint==0.3.0
      - oci==2.164.0
      - ocifs==1.3.4
      - omegaconf==2.3.0
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - panel==1.8.3
      - param==2.3.0
      - paramiko==4.0.0
      - partd==1.4.2
      - pathvalidate==3.3.1
      - peft==0.18.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - ply==3.11
      - portalocker==3.2.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycparser==2.23
      - pycryptodomex==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygit2==1.19.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynacl==1.6.1
      - pynvml==13.0.1
      - pyopenssl==25.1.0
      - pyparsing==3.2.5
      - pyspnego==0.12.0
      - pytablewriter==1.2.1
      - python-daemon==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.1.0+cf34004b8a
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rouge-score==0.1.2
      - rpds-py==0.29.0
      - rsa==4.9.1
      - s3fs==2025.3.0
      - sacrebleu==2.5.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - six==1.17.0
      - smbprotocol==1.15.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sqlitedict==2.1.0
      - stone==3.3.1
      - submitit==1.5.3
      - sympy==1.13.1
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tblib==3.2.2
      - tcolorpy==0.1.7
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toolz==1.1.0
      - torch==2.6.0.dev20241112+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.57.3
      - typepy==1.3.4
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - viztracer==1.1.1
      - wandb==0.23.0
      - webencodings==0.5.1
      - word2number==1.1
      - wrapt==1.17.3
      - xformers==0.0.29+de742ec.d20251125
      - xxhash==3.6.0
      - xyzservices==2025.11.0
      - yarl==1.22.0
      - zict==3.0.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/dyntok
