train:
  _target_: datasets.load_dataset
  path: "roneneldan/TinyStories"
  split: "train[:50%]"
  cache_dir: ${core.dataset_path}

validation:
  _target_: datasets.load_dataset
  path: "roneneldan/TinyStories"
  split: "validation[:50%]"
  cache_dir: ${core.dataset_path}

test:
  _target_: datasets.load_dataset
  path: "roneneldan/TinyStories"
  split: "validation[50%:]"
  cache_dir: ${core.dataset_path}

batch_size: 64
seq_length: 256
name: tinystories
