# Default Configurations 
defaults:
  - _self_
  - dataset: tinyshakespeare
  - model: blt_1b
  - lora: standard
  - method: attention
  - optimizer: AdamW8bit

# Hyperparameters 
hyperparameters:
  storage_path: /leonardo_scratch/fast/IscrC_ELLIF-HE/federicoalvetreti
  experiment_name : prova
  seed: 332

# Set folders for results, datasets and plots 
core:
  dataset_path: ${hyperparameters.storage_path}/data
  models_path: ${hyperparameters.storage_path}/models
  results_path: ${hyperparameters.storage_path}/results
  plots_path : ${hyperparameters.storage_path}/plots


# Set default Hydra folder name 
hydra:
 run:
   dir: ${core.results_path}/${hyperparameters.experiment_name}_${hyperparameters.seed}/${dataset.name}/${model.model_name}/${method.name}//params=${method.parameters}

 job_logging:
   root:
     level: WARNING